// supabase/functions/generate-meal-plan/meal-ideas.ts
// A bank of healthy meal ideas. Each plan gets a random handful per slot, so the model
// starts from different dishes every time. Add or edit ideas freely; the more, the better.

import { shuffle } from "./variety.ts";

export const MEAL_IDEAS: Record<string, string[]> = {
  breakfast: [
    "Veggie egg muffins with feta",
    "Greek yogurt parfait with berries and granola",
    "Overnight oats with chia and peanut butter",
    "Shakshuka with whole-grain toast",
    "Protein banana pancakes",
    "Avocado toast with a poached egg",
    "Sweet potato and black bean breakfast hash",
    "Smoked salmon and cucumber on a whole-grain bagel thin",
    "Cottage cheese bowl with pineapple and pumpkin seeds",
    "Tofu scramble with peppers and spinach",
    "Breakfast burrito with eggs, beans, and salsa",
    "Chia pudding with mango and coconut",
    "Spinach and mushroom omelet with fruit",
    "Quinoa breakfast bowl with cinnamon apples and almonds",
    "Turkey sausage and veggie skillet",
    "Peanut butter banana oat smoothie",
    "Green smoothie with spinach, pineapple, and protein powder",
    "Ricotta toast with berries and honey",
    "Steel-cut oats with walnuts and pears",
    "Egg and vegetable breakfast fried rice",
    "Whole-grain waffle with Greek yogurt and strawberries",
    "Baked blueberry oatmeal",
    "Huevos rancheros with black beans",
    "Zucchini and cheddar frittata",
    "Miso-egg rice bowl with greens",
    "Savory oatmeal with a soft egg and scallions",
    "Chickpea flour veggie pancake (besan chilla)",
    "Cottage cheese pancakes with berries",
    "Breakfast salad with a soft-boiled egg and greens",
    "Apple-cinnamon protein oats",
  ],
  lunch: [
    "Chicken and quinoa Buddha bowl",
    "Turkey and hummus whole-wheat wrap",
    "Red lentil soup with lemon",
    "Tuna and white bean salad",
    "Chicken shawarma bowl with cucumber-tomato salad",
    "Black bean and corn burrito bowl",
    "Salmon poke-style bowl",
    "Shrimp and avocado salad",
    "Chickpea salad sandwich",
    "Thai peanut chicken lettuce wraps",
    "Greek salad with grilled chicken and tzatziki",
    "Caprese chicken over mixed greens",
    "Beef and broccoli stir-fry over brown rice",
    "Egg roll in a bowl with ground turkey",
    "Falafel bowl with tahini sauce",
    "Tofu banh mi bowl",
    "Minestrone with white beans",
    "Teriyaki chicken and edamame rice bowl",
    "Southwest chicken salad with lime dressing",
    "Farro salad with roasted vegetables and feta",
    "Tuna-stuffed avocado",
    "Sesame soba noodle salad with tofu",
    "Chicken pho-style noodle soup",
    "Curried chickpea and spinach stew",
    "Bibimbap-style bowl with vegetables and egg",
    "Turkey taco lettuce cups",
    "Roasted vegetable and hummus pita",
    "Pesto chicken and tomato whole-grain pasta salad",
    "Chicken tortilla soup",
    "Salmon salad with dill yogurt dressing",
    "Gyro-style turkey bowl",
    "Lemon chicken orzo soup",
    "Sweet potato and black bean quesadilla",
    "Cobb salad with grilled chicken",
    "Tempeh and vegetable grain bowl",
  ],
  dinner: [
    "Baked salmon with lemon-dill, roasted broccoli, and quinoa",
    "Chicken tikka masala with basmati rice and greens",
    "Sheet-pan chicken fajitas",
    "Turkey meatballs with zucchini noodles and marinara",
    "Shrimp stir-fry with snap peas and brown rice",
    "Lean beef and vegetable chili",
    "Herb-crusted cod with roasted potatoes and green beans",
    "Pork tenderloin with apple slaw and roasted carrots",
    "Thai green curry with tofu and vegetables",
    "Stuffed bell peppers with turkey and rice",
    "Lemon-garlic chicken thighs with roasted Brussels sprouts",
    "Miso-glazed salmon with bok choy",
    "Black bean and sweet potato enchilada bake",
    "Flank steak with chimichurri and grilled vegetables",
    "Chana masala with brown rice",
    "Shrimp tacos with cabbage slaw",
    "Moroccan chicken tagine with chickpeas",
    "Lightened eggplant parmesan bake",
    "Teriyaki tofu stir-fry with broccoli",
    "Greek chicken souvlaki with tabbouleh",
    "Korean beef bulgogi bowl",
    "Seared tuna with sesame greens and rice",
    "Turkey and vegetable stuffed zucchini boats",
    "Coconut lentil dal with spinach",
    "Baked chicken parmesan with a side salad",
    "Lemongrass chicken with rice noodles and herbs",
    "Spaghetti squash with turkey bolognese",
    "Mushroom and spinach lasagna roll-ups",
    "Blackened tilapia with mango salsa and rice",
    "Chicken and shrimp jambalaya with brown rice",
    "Slow-cooker pulled chicken with roasted sweet potato",
    "Ginger-soy cod with steamed vegetables",
    "Peruvian-style roast chicken with green sauce and salad",
    "Ethiopian-style lentil stew (misir wot) with greens",
    "Sesame-crusted salmon with soba noodles",
    "Pork and vegetable stir-fry with ginger",
    "Turkey burger with baked sweet potato fries and salad",
    "Tuscan white bean and kale soup with grilled chicken",
    "Paella-style rice with shrimp, peas, and peppers",
    "Stuffed portobello mushrooms with quinoa and feta",
  ],
  snack: [
    "Apple slices with almond butter",
    "Greek yogurt with honey and walnuts",
    "Hummus with carrot and cucumber sticks",
    "Cottage cheese with berries",
    "Roasted chickpeas",
    "Hard-boiled eggs with everything seasoning",
    "Edamame with sea salt",
    "Trail mix with nuts and dark chocolate",
    "Turkey and cheese roll-ups",
    "Banana with peanut butter",
    "Berry protein smoothie",
    "Cheese stick with whole-grain crackers",
    "Guacamole with veggie sticks",
    "Chia pudding cup",
    "Tuna on cucumber slices",
    "Oat and date energy bites",
    "Ricotta with sliced pear and cinnamon",
    "Air-popped popcorn with parmesan",
    "Tzatziki with bell pepper strips",
    "Almonds and a clementine",
    "Smoked salmon and cream cheese cucumber bites",
    "Baked apple chips with Greek yogurt dip",
    "Mini caprese skewers",
    "Peanut butter protein balls",
    "Kefir with berries",
    "Sliced turkey with avocado",
  ],
};

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9 ]/g, "").trim();

// Picks `n` random ideas per meal slot, skipping any that match a recently planned meal.
export function buildIdeasPrompt(avoid: string[], n = 4): string {
  const recent = avoid.map(norm);
  const lines = [
    "MEAL IDEA BANK (this plan's starting points):",
    "- For each meal, choose ONE idea from its list and adapt it to the user's allergies, dietary preferences, pantry, and calorie/protein targets.",
    "- If none of the listed ideas fit the user's restrictions, create a clearly different healthy dish instead.",
  ];
  for (const [slot, ideas] of Object.entries(MEAL_IDEAS)) {
    const fresh = ideas.filter((i) => !recent.some((r) => r && (r.includes(norm(i)) || norm(i).includes(r))));
    const picks = shuffle(fresh.length >= n ? fresh : ideas).slice(0, n);
    lines.push(`- ${slot}: ${picks.join(" | ")}`);
  }
  return lines.join("\n");
}
